### ISSUE TITLE
Document debugging assets

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientOrg/Ambient#118]
"Look in the target/assets folder"..

**Comment by philpax** [comment]
Is there anything else we want to mention other than "look in target"? What should people look for?

We also have a Vec OutAsset in the pipeline - we should dump that to json and put it in target.

Do we also want to rename the folder to `build` so that Rust won't spew all of its intermediaries over it if you're doing a single project workspace?

**Comment by FredrikNoren** [comment]
Renaming to build; yeah I was thinking the same
OutAssets; yes, that's what the editor will eventually use to figure out what assets are actually available

**Comment by philpax** [comment]
Done, I've renamed `target` to `build` and added a little section to Debugging about it. OutAsset thing can be another issue
